version: 0.2.19.{build}

#environment:

platform: 
  - x64

configuration: Release

clone_folder: c:\projects\OpenBLAS

init:
  - git config --global core.autocrlf input

clone_depth: 5

skip_tags: true

matrix:
  fast_finish: false

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

environment:
  global:
    CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
  matrix:
    - COMPILER: clang-cl
      DYNAMIC_ARCH: ON
      WITH_FORTRAN: yes
    - COMPILER: clang-cl
      DYNAMIC_ARCH: ON
      WITH_FORTRAN: no
    - COMPILER: cl
      DYNAMIC_ARCH: OFF

install:
  - if [%COMPILER%]==[clang-cl] call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - if [%COMPILER%]==[clang-cl] conda config --add channels conda-forge --force
  - if [%WITH_FORTRAN%]==[yes] conda config --add channels isuruf/label/flang --force
  - if [%COMPILER%]==[clang-cl] conda install --yes --quiet clangdev ninja cmake
  - if [%WITH_FORTRAN%]==[yes] conda install --yes --quiet flangdev clangdev cmake jom
  - if [%COMPILER%]==[clang-cl] call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - if [%COMPILER%]==[clang-cl] set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
  - if [%COMPILER%]==[clang-cl] set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"

before_build:
  - echo Running cmake...
  - cd c:\projects\OpenBLAS
  - if [%COMPILER%]==[cl] cmake -G "Visual Studio 12 Win64" .
  - if [%WITH_FORTRAN%]==[no] cmake -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DDYNAMIC_ARCH=%DYNAMIC_ARCH% .
  - if [%WITH_FORTRAN%]==[yes] cmake -G "NMake Makefiles JOM" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=%DYNAMIC_ARCH% .

build_script:
  - if [%WITH_FORTRAN%]==[yes] jom
  - cmake --build .
  - ps: Compress-Archive -Path C:\projects\OpenBLAS\build\lib -DestinationPath C:\Projects\OpenBLAS\lib.zip
  - ps: Push-AppveyorArtifact C:\Projects\OpenBLAS\lib.zip

test_script:
  - echo Running Test
  - cd c:\projects\OpenBLAS\utest
  - openblas_utest

